### ISSUE TITLE
How to generate a .csv file from training data

### ISSUE THREAD

**Issue by shiyajing111** [talhajamal11/LSTM-RNN-for-Human-Activity-Recognition#2]

**Comment by talhajamal11** [comment]
I'm assuming you're asking how to output a certain list from the training data into a CSV file?

For that, you will need to import the CSV library. Alter the list however you like. The following sample code should work:

```python
import csv

with open('filename', 'wb') as myfile:
    wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
    wr.writerow(mylist)
```

This should work for python 2.x, I believe. For python 3.x you may have to change 'wb' into 'w'.

**Comment by talhajamal11** [comment]
If the training_data is a pandas dataframe, you can use the command “to_csv” to export it as a csv file. 

“training_data.to_csv()”
